namespace: devopsarr
name: prowlarr
# Version will be updated by workflow
version: 0.0.1
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: "Ansible collection for Prowlarr"
license_file: LICENSE
tags:
  - prowlarr
  - arr
  - indexer
repository: https://github.com/devopsarr/ansible-collection-prowlarr
#documentation: https://github.com/ansible-collection-migration/devopsarr.prowlarr/tree/main/docs
homepage: https://github.com/devopsarr/ansible-collection-prowlarr
issues: https://github.com/devopsarr/ansible-collection-prowlarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml