namespace: devopsarr
name: prowlarr
version: 1.0.0 # x-release-please-version
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: 'Ansible collection for Prowlarr'
license_file: LICENSE
tags:
  - prowlarr
  - arr
  - indexer
repository: https://github.com/devopsarr/ansible-collection-prowlarr
documentation: https://devopsarr.github.io/ansible-doc/collections/devopsarr/prowlarr/
homepage: https://github.com/devopsarr/ansible-collection-prowlarr
issues: https://github.com/devopsarr/ansible-collection-prowlarr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml
