# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: devopsarr
name: prowlarr
version: 0.1.0
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: null
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - example1
  - example2
repository: https://github.com/ansible-collections/devopsarr.prowlarr
#documentation: https://github.com/ansible-collection-migration/devopsarr.prowlarr/tree/main/docs
homepage: https://github.com/ansible-collections/devopsarr.prowlarr
issues: https://github.com/ansible-collections/devopsarr.prowlarr/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
